CREATE TABLE pemesanan_bus (
    id INT PRIMARY KEY AUTO_INCREMENT,
    id_user INT NOT NULL,
    id_bus INT NOT NULL,
    tanggal_pemesanan DATETIME NOT NULL,
    tanggal_berangkat DATE NOT NULL,
    waktu_berangkat TIME NOT NULL,
    kota_asal VARCHAR(100) NOT NULL,
    nama_pemesan VARCHAR(100) NOT NULL,
    kontak_pemesan VARCHAR(20) NOT NULL,
    kota_tujuan VARCHAR(100) NOT NULL,
    jumlah_penumpang INT NOT NULL,
    total_harga DECIMAL(10,2) NOT NULL,
    status ENUM('pending', 'dibayar_dp', 'dibayar', 'ditolak', 'dibatalkan', 'selesai') NOT NULL DEFAULT 'pending',
    catatan TEXT,
    bukti_pembayaran VARCHAR(255),
    jenis_pembayaran ENUM('dp', 'lunas') NOT NULL,
    jumlah_bayar DECIMAL(10,2) NOT NULL,
    created_at DATETIME NOT NULL,
    pembayaran_dp DECIMAL(10,2) DEFAULT 0,
    dp_created_at DATETIME,
    sisa_pembayaran DECIMAL(10,2) DEFAULT 0,
    titik_jemput TEXT,
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    FOREIGN KEY (id_user) REFERENCES users(id),
    FOREIGN KEY (id_bus) REFERENCES bus(id)
); 